dofile("src/underscore.lua")
_ = Underscore.funcs
dofile("src/MiddleClass.lua")
dofile("src/event.lua")
dofile("src/game.lua")
dofile("src/unit.lua")
dofile("src/squadron.lua")
dofile("src/option.lua")
dofile("src/player.lua")
dofile("src/round.lua")
dofile("src/turn.lua")
dofile("src/debug.lua")
dofile("src/functions.lua")
dofile("src/gui_object.lua")
dofile("src/turn_panel.lua")
dofile("src/tweener.lua")
