_ = dofile("src/underscore.lua")
dofile "src/MiddleClass.lua"
dofile "src/event.lua"
dofile "src/elf_object.lua"
dofile "src/game.lua"
dofile "src/unit.lua"
dofile "src/squadron.lua"
dofile "src/option.lua"
dofile "src/player.lua"
dofile "src/round.lua"
dofile "src/turn.lua"
dofile "src/debug.lua"
dofile "src/functions.lua"
dofile "src/turn_panel.lua"
dofile "src/tweener.lua"
dofile "src/current_panel.lua"
dofile "src/loader.lua"
dofile "src/progress_bar.lua"
dofile "src/mini_panel.lua"
dofile "src/units_panel.lua"
dofile "src/weapon.lua"
dofile "src/weapon_panel.lua"

